version: '2'
services:
  mysql:
    image: mysql
    restart: always
    volumes:
    - ./conf/mysql/mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
    environment:
      - MYSQL_ROOT_PASSWORD=pa$$w0wd
      - MYSQL_DATABASE=typecho
      - MYSQL_USER=typecho
      - MYSQL_PASSWORD=foobar
  nginx:
    image: nginx:stable
    restart: always
    volumes:
      - ./conf/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./conf/nginx/cert:/etc/nginx/cert
      - ./data/www:/var/www/html
    ports:
      - 443:443
      - 80:80
    links:
      - php
  php:
    image: php:yourtag
    restart: always
    volumes:
      - ./data/www:/var/www/html
    links:
      - mysql
